"""Initial schema

Revision ID: 720787691d58
Revises: 
Create Date: 2025-12-20 21:51:14.622392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '720787691d58'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('networks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('last_layout_name', sa.String(), nullable=True),
    sa.Column('last_node_size_config', sa.JSON(), nullable=True),
    sa.Column('last_node_color_config', sa.JSON(), nullable=True),
    sa.Column('last_edge_width_config', sa.JSON(), nullable=True),
    sa.Column('last_edge_color_config', sa.JSON(), nullable=True),
    sa.Column('last_node_label_config', sa.JSON(), nullable=True),
    sa.Column('parent_network_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_network_id'], ['networks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_networks_id'), 'networks', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('chats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('network_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('visualization_state', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['network_id'], ['networks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('network_id')
    )
    op.create_index(op.f('ix_chats_id'), 'chats', ['id'], unique=False)
    op.create_table('edge_attributes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('network_id', sa.Integer(), nullable=False),
    sa.Column('attribute_name', sa.String(), nullable=False),
    sa.Column('data_type', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['network_id'], ['networks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('network_id', 'attribute_name', name='unique_network_edge_attr')
    )
    op.create_index(op.f('ix_edge_attributes_id'), 'edge_attributes', ['id'], unique=False)
    op.create_table('node_attributes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('network_id', sa.Integer(), nullable=False),
    sa.Column('attribute_name', sa.String(), nullable=False),
    sa.Column('data_type', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['network_id'], ['networks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('network_id', 'attribute_name', name='unique_network_node_attr')
    )
    op.create_index(op.f('ix_node_attributes_id'), 'node_attributes', ['id'], unique=False)
    op.create_table('nodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('network_id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['network_id'], ['networks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('network_id', 'node_id', name='unique_network_node')
    )
    op.create_index(op.f('ix_nodes_id'), 'nodes', ['id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_id'), 'chat_messages', ['id'], unique=False)
    op.create_table('edges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('network_id', sa.Integer(), nullable=False),
    sa.Column('edge_id', sa.String(), nullable=False),
    sa.Column('source_node_id', sa.Integer(), nullable=False),
    sa.Column('target_node_id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['network_id'], ['networks.id'], ),
    sa.ForeignKeyConstraint(['source_node_id'], ['nodes.id'], ),
    sa.ForeignKeyConstraint(['target_node_id'], ['nodes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('network_id', 'edge_id', name='unique_network_edge')
    )
    op.create_index(op.f('ix_edges_id'), 'edges', ['id'], unique=False)
    op.create_table('node_attribute_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('attribute_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['attribute_id'], ['node_attributes.id'], ),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('node_id', 'attribute_id', name='unique_node_attr_val')
    )
    op.create_index(op.f('ix_node_attribute_values_id'), 'node_attribute_values', ['id'], unique=False)
    op.create_table('edge_attribute_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('edge_id', sa.Integer(), nullable=False),
    sa.Column('attribute_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['attribute_id'], ['edge_attributes.id'], ),
    sa.ForeignKeyConstraint(['edge_id'], ['edges.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('edge_id', 'attribute_id', name='unique_edge_attr_val')
    )
    op.create_index(op.f('ix_edge_attribute_values_id'), 'edge_attribute_values', ['id'], unique=False)
    op.create_table('node_float_attribute_values',
    sa.Column('node_attribute_value_id', sa.Integer(), nullable=False),
    sa.Column('float_value', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['node_attribute_value_id'], ['node_attribute_values.id'], ),
    sa.PrimaryKeyConstraint('node_attribute_value_id')
    )
    op.create_table('node_text_attribute_values',
    sa.Column('node_attribute_value_id', sa.Integer(), nullable=False),
    sa.Column('text_value', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['node_attribute_value_id'], ['node_attribute_values.id'], ),
    sa.PrimaryKeyConstraint('node_attribute_value_id')
    )
    op.create_table('edge_float_attribute_values',
    sa.Column('edge_attribute_value_id', sa.Integer(), nullable=False),
    sa.Column('float_value', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['edge_attribute_value_id'], ['edge_attribute_values.id'], ),
    sa.PrimaryKeyConstraint('edge_attribute_value_id')
    )
    op.create_table('edge_text_attribute_values',
    sa.Column('edge_attribute_value_id', sa.Integer(), nullable=False),
    sa.Column('text_value', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['edge_attribute_value_id'], ['edge_attribute_values.id'], ),
    sa.PrimaryKeyConstraint('edge_attribute_value_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('edge_text_attribute_values')
    op.drop_table('edge_float_attribute_values')
    op.drop_table('node_text_attribute_values')
    op.drop_table('node_float_attribute_values')
    op.drop_index(op.f('ix_edge_attribute_values_id'), table_name='edge_attribute_values')
    op.drop_table('edge_attribute_values')
    op.drop_index(op.f('ix_node_attribute_values_id'), table_name='node_attribute_values')
    op.drop_table('node_attribute_values')
    op.drop_index(op.f('ix_edges_id'), table_name='edges')
    op.drop_table('edges')
    op.drop_index(op.f('ix_chat_messages_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_nodes_id'), table_name='nodes')
    op.drop_table('nodes')
    op.drop_index(op.f('ix_node_attributes_id'), table_name='node_attributes')
    op.drop_table('node_attributes')
    op.drop_index(op.f('ix_edge_attributes_id'), table_name='edge_attributes')
    op.drop_table('edge_attributes')
    op.drop_index(op.f('ix_chats_id'), table_name='chats')
    op.drop_table('chats')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_networks_id'), table_name='networks')
    op.drop_table('networks')
    # ### end Alembic commands ###
