"""Initial migration

Revision ID: 8267a8df8650
Revises: 
Create Date: 2025-12-20 19:21:25.001607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8267a8df8650'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_conversations_user_id'), table_name='conversations')
    op.drop_table('conversations')
    op.add_column('chat_messages', sa.Column('chat_id', sa.Integer(), nullable=False))
    op.add_column('chat_messages', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('chat_messages', 'meta_data',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::text"))
    op.drop_index(op.f('idx_chat_messages_conversation_id'), table_name='chat_messages')
    op.drop_index(op.f('idx_chat_messages_user_id'), table_name='chat_messages')
    op.create_index(op.f('ix_chat_messages_id'), 'chat_messages', ['id'], unique=False)
    op.drop_constraint(op.f('chat_messages_user_id_fkey'), 'chat_messages', type_='foreignkey')
    op.drop_constraint(op.f('chat_messages_conversation_id_fkey'), 'chat_messages', type_='foreignkey')
    op.create_foreign_key(None, 'chat_messages', 'chats', ['chat_id'], ['id'])
    op.drop_column('chat_messages', 'conversation_id')
    op.drop_column('chat_messages', 'user_id')
    op.alter_column('chats', 'visualization_state',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('networks', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'Untitled Network'::character varying"))
    op.drop_index(op.f('idx_networks_conversation_id'), table_name='networks')
    op.drop_constraint(op.f('networks_conversation_id_key'), 'networks', type_='unique')
    op.create_index(op.f('ix_networks_id'), 'networks', ['id'], unique=False)
    op.drop_constraint(op.f('networks_conversation_id_fkey'), 'networks', type_='foreignkey')
    op.drop_column('networks', 'graphml_content')
    op.drop_column('networks', 'conversation_id')
    op.drop_constraint(op.f('users_username_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.create_unique_constraint(op.f('users_username_key'), 'users', ['username'], postgresql_nulls_not_distinct=False)
    op.add_column('networks', sa.Column('conversation_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('networks', sa.Column('graphml_content', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('networks_conversation_id_fkey'), 'networks', 'conversations', ['conversation_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_networks_id'), table_name='networks')
    op.create_unique_constraint(op.f('networks_conversation_id_key'), 'networks', ['conversation_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_networks_conversation_id'), 'networks', ['conversation_id'], unique=False)
    op.alter_column('networks', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'Untitled Network'::character varying"))
    op.alter_column('chats', 'visualization_state',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.add_column('chat_messages', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('chat_messages', sa.Column('conversation_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'chat_messages', type_='foreignkey')
    op.create_foreign_key(op.f('chat_messages_conversation_id_fkey'), 'chat_messages', 'conversations', ['conversation_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('chat_messages_user_id_fkey'), 'chat_messages', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_chat_messages_id'), table_name='chat_messages')
    op.create_index(op.f('idx_chat_messages_user_id'), 'chat_messages', ['user_id'], unique=False)
    op.create_index(op.f('idx_chat_messages_conversation_id'), 'chat_messages', ['conversation_id'], unique=False)
    op.alter_column('chat_messages', 'meta_data',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::text"))
    op.drop_column('chat_messages', 'updated_at')
    op.drop_column('chat_messages', 'chat_id')
    op.create_table('conversations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), server_default=sa.text("'New Conversation'::character varying"), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('conversations_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('conversations_pkey'))
    )
    op.create_index(op.f('idx_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    # ### end Alembic commands ###
